### ISSUE TITLE
Unable to search items by sku

### ISSUE THREAD

**Issue by shesmu** [bhushankumarl/amazon-mws#45]
GetLowestPricedOffersForSKU,
GetCompetitivePricingForSKU,
GetLowestOfferListingsForSKU,
GetLowestPricedOffersForSKU,
GetMyPriceForSKU,
GetProductCategoriesForSKU.

All return "XXXXX-XXXX-XX is an invalid SellerSKU for marketplace XXXXXXX".
Have tried all marketplaces and a wide variety of skus that are currently in use and not examples, including skus that my actual products have so I know for a fact some of them are valid. There is a chance this is on amazons end but seems rather unlikely as I have not seen many mentions of this issue.

**Comment by bhushankumarl** [comment]
@shesmu 
Would you please provide sample API request that you are doing?

**Comment by shesmu** [comment]
amazonMws.products.searchFor({
		'Version': '2011-10-01',
		'Action': 'GetMyPriceForSKU',
		'SellerId': seller_id,
		'MWSAuthToken': auth_token,
		'MarketplaceId': marketplace_id,
		'SellerSKUList.SellerSKU.1': '6000196765166',
		'ItemCondition': 'New'
	}, function (error, response) {
		if (error) {
			console.log('error ', error);
			return;
		}
		
		console.log('response ', response);
	});

**Comment by shesmu** [comment]
MarketplaceId in this case is 'A2EUQ1WTGCTBG2'.

**Comment by bhushankumarl** [comment]
@shesmu Please send exact error response that you are receiving from this API call.

**Comment by shesmu** [comment]
This is the full error message I am receiving.

response  { SellerSKU: '6000196765166',
  status: 'ClientError',
  Error: 
   { Type: 'Sender',
     Code: 'InvalidParameterValue',
     Message: '6000196765166 is an invalid SellerSKU for marketplace A2EUQ1WTGCTBG2' },
  ResponseMetadata: { RequestId: 'ab8a25c6-849e-428b-b920-958078c62552' },
  Headers: 
   { 'x-mws-quota-max': '36000.0',
     'x-mws-quota-remaining': '35999.0',
     'x-mws-quota-resetson': '2018-08-23T13:35:00.000Z',
     'x-mws-timestamp': '2018-08-23T13:27:53.800Z',
     'content-type': 'text/xml',
     'content-charset': 'unknown',
     'content-length': 'unknown',
     'content-md5': 'unknown',
     date: 'Thu, 23 Aug 2018 13:27:53 GMT' } }

**Comment by shesmu** [comment]
@bhushankumarl 

I have validated my values on the scratchpad and got the same error for invalid seller sku, no mention of incorrect values, also when using the api wrapper most other commands work perfectly so I pretty sure all the values are correct.

Have you been able to replicate this issue or is it just on my end?

**Comment by bhushankumarl** [comment]
@shesmu 
I validated the request. After doing some research I found that you using the wrong combination of the SellerSKU and Marketplace Id.

In error response, you can see the `Message` which has been sent back by the Amazon itself which confirm the same.

You can use the  `RequestId` and contact to the Amazon Marketplace form to dig deep into this issue.

**Comment by KyleJune** [comment]
@shesmu I'm not using this client but came across the same issue when trying to get the products by SellerSKU using all the SellerSKU values from the Amazon open listings report. The open listings report contains all of their products, including inactive ones. If an inactive product(out of stock) for a long time, then the listing for the ASIN associated with that product gets deleted from amazon. When that happens, the product API will no longer return that product even though you have the correct SellerSKU because it is considered to be no longer at the marketplace once the listing for the ASIN is deleted.

Hope this helps anyone else that finds this when searching for why they are getting error code 'InvalidParameterValue' from the product API even though the product exists on the account.
